//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.TeamProject.RealEstateAgency
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class HOPDONG
    {
        public int MAHD { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MANHA { get; set; }
        public Nullable<int> MACN { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string GHICHU { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
