//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.TeamProject.RealEstateAgency
{
    using PropertyChanged;
    using System;

    [AddINotifyPropertyChangedInterface]
    public partial class KEHOACHXEMNHA
    {
        public int MAKH { get; set; }
        public int MANV { get; set; }
        public int MANHA { get; set; }
        public Nullable<int> MACN { get; set; }
        public Nullable<System.DateTime> NGAYXEM { get; set; }
        public string NHANXET { get; set; }

        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
