//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.TeamProject.RealEstateAgency
{
    using PropertyChanged;
    using System.Collections.ObjectModel;

    [AddINotifyPropertyChangedInterface]
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOPDONGs = new ObservableCollection<HOPDONG>();
            this.KEHOACHXEMNHAs = new ObservableCollection<KEHOACHXEMNHA>();
            this.YEUCAUs = new ObservableCollection<YEUCAU>();
        }

        public int MAKH { get; set; }
        public int CNQUANLY { get; set; }
        public string TEN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string CHITIET { get; set; }

        public virtual CHINHANH CHINHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<HOPDONG> HOPDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<KEHOACHXEMNHA> KEHOACHXEMNHAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<YEUCAU> YEUCAUs { get; set; }
    }
}
